-- 万物有灵 - Supabase数据库初始化脚本
-- 在Supabase的SQL Editor中执行此脚本

-- ==================== 用户表 ====================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    device_id VARCHAR(255) UNIQUE,
    avatar_url TEXT,
    preferences JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_users_device_id ON users(device_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);

-- 添加注释
COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.device_id IS '设备ID，用于匿名用户识别';
COMMENT ON COLUMN users.preferences IS '用户偏好设置（JSON格式）';

-- ==================== 对话表 ====================
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL DEFAULT '新对话',
    spirit_name VARCHAR(100) DEFAULT '万物之灵',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created_at ON conversations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_is_active ON conversations(is_active);

-- 添加注释
COMMENT ON TABLE conversations IS '对话表';
COMMENT ON COLUMN conversations.spirit_name IS '灵体名称，如"茶壶地灵"';

-- ==================== 消息表 ====================
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    emotion_data JSONB, -- 心情分析数据
    weather_data JSONB, -- 天气数据
    image_info JSONB,   -- 图片信息
    metadata JSONB DEFAULT '{}'::jsonb, -- 其他元数据
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);
CREATE INDEX IF NOT EXISTS idx_messages_role ON messages(role);

-- 添加注释
COMMENT ON TABLE messages IS '消息表';
COMMENT ON COLUMN messages.emotion_data IS '心情分析结果（JSON格式）';
COMMENT ON COLUMN messages.weather_data IS '天气信息（JSON格式）';
COMMENT ON COLUMN messages.image_info IS '图片识别信息（JSON格式）';

-- ==================== 位置记录表 ====================
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    address TEXT,
    weather_data JSONB, -- 该位置的天气数据
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_locations_user_id ON locations(user_id);
CREATE INDEX IF NOT EXISTS idx_locations_created_at ON locations(created_at DESC);

-- 添加PostGIS扩展（如果需要地理空间查询）
-- CREATE EXTENSION IF NOT EXISTS postgis;

-- 添加注释
COMMENT ON TABLE locations IS '用户位置记录表';
COMMENT ON COLUMN locations.latitude IS '纬度，范围-90到90';
COMMENT ON COLUMN locations.longitude IS '经度，范围-180到180';

-- ==================== 图片记录表 ====================
CREATE TABLE IF NOT EXISTS images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    conversation_id BIGINT REFERENCES conversations(id) ON DELETE SET NULL,
    image_data TEXT NOT NULL, -- Base64编码的图片
    image_url TEXT, -- 如果使用存储，这里是URL
    file_name VARCHAR(255),
    file_size INTEGER,
    mime_type VARCHAR(100),
    analysis_result JSONB, -- 图片识别结果
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_images_user_id ON images(user_id);
CREATE INDEX IF NOT EXISTS idx_images_conversation_id ON images(conversation_id);
CREATE INDEX IF NOT EXISTS idx_images_created_at ON images(created_at DESC);

-- 添加注释
COMMENT ON TABLE images IS '用户上传的图片记录';
COMMENT ON COLUMN images.image_data IS 'Base64编码的图片数据';
COMMENT ON COLUMN images.analysis_result IS '图片识别和分析结果（JSON格式）';

-- ==================== 心情记录表（可选）====================
CREATE TABLE IF NOT EXISTS emotion_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    emotion VARCHAR(50) NOT NULL, -- 主要情绪
    emotion_data JSONB, -- 详细情绪分析
    intensity DECIMAL(3, 2), -- 情绪强度0-1
    context TEXT, -- 上下文
    message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_emotion_history_user_id ON emotion_history(user_id);
CREATE INDEX IF NOT EXISTS idx_emotion_history_emotion ON emotion_history(emotion);
CREATE INDEX IF NOT EXISTS idx_emotion_history_created_at ON emotion_history(created_at DESC);

-- 添加注释
COMMENT ON TABLE emotion_history IS '用户情绪历史记录';

-- ==================== 创建更新触发器 ====================

-- 用户表更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_conversations_updated_at BEFORE UPDATE ON conversations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==================== Row Level Security (RLS) ====================

-- 启用RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE images ENABLE ROW LEVEL SECURITY;
ALTER TABLE emotion_history ENABLE ROW LEVEL SECURITY;

-- 创建策略（根据需要调整）

-- 用户只能访问自己的数据（通过device_id或认证）
CREATE POLICY "Users can view own data" ON users
    FOR SELECT USING (
        device_id IN (
            SELECT device_id FROM users WHERE id = auth.uid()
        )
    );

-- ==================== 视图（用于复杂查询）====================

-- 用户对话统计视图
CREATE OR REPLACE VIEW user_conversation_stats AS
SELECT
    u.id AS user_id,
    u.username,
    COUNT(DISTINCT c.id) AS total_conversations,
    COUNT(DISTINCT m.id) AS total_messages,
    COUNT(DISTINCT i.id) AS total_images,
    MAX(c.created_at) AS last_conversation_at
FROM users u
LEFT JOIN conversations c ON u.id = c.user_id
LEFT JOIN messages m ON c.id = m.conversation_id
LEFT JOIN images i ON u.id = i.user_id
GROUP BY u.id, u.username;

COMMENT ON VIEW user_conversation_stats IS '用户对话统计视图';

-- ==================== 初始化测试数据（可选）====================

-- 插入测试用户
INSERT INTO users (username, device_id)
VALUES ('测试用户', 'test_device_001')
ON CONFLICT (device_id) DO NOTHING;

-- ==================== 完成 ====================

-- 显示创建的表
SELECT
    table_name,
    obj_description(table_name, 'pg_class') AS comment
FROM information_schema.tables
WHERE table_schema = 'public'
    AND table_name IN ('users', 'conversations', 'messages', 'locations', 'images', 'emotion_history')
ORDER BY table_name;
